name: Update Sensor Data

on:
  repository_dispatch:
    types: [sensor-data]

jobs:
  update-sensor-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug received data
        run: |
          echo "📊 Получены данные от ESP8266:"
          echo '${{ toJson(github.event.client_payload) }}'
          
      - name: Update data.json file
        run: |
          # Создаем обновленный data.json
          cat > docs/data.json << EOF
          {
            "temperature": ${{ github.event.client_payload.temperature }},
            "humidity": ${{ github.event.client_payload.humidity }},
            "voltage": ${{ github.event.client_payload.voltage }},
            "lastUpdate": "${{ fromJSON('{"now": "2024-01-01"}').now }}",
            "status": "success"
          }
          EOF
          
      - name: Show updated file content
        run: |
          echo "📄 Обновленный data.json:"
          cat docs/data.json
          
      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add docs/data.json
          git commit -m "🤖 Auto-update sensor data: ${{ github.event.client_payload.temperature }}°C, ${{ github.event.client_payload.humidity }}%"
          git push
