name: Update Sensor Data

on:
  repository_dispatch:
    types: [sensor-data]

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Update data file
        run: |
          echo '${{ toJson(github.event.client_payload) }}' > docs/data.json
          
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/data.json
          git commit -m "Update sensor data: ${{ github.event.client_payload.t }}°C, ${{ github.event.client.client_payload.h }}%"
          git push
